# Generated by Django 3.2 on 2021-04-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('artists', models.URLField()),
                ('tracks', models.URLField()),
                ('self_url', models.URLField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
        ),
    ]
