# Generated by Django 3.2 on 2021-04-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('times_played', models.IntegerField()),
                ('albums', models.URLField()),
                ('artists', models.URLField()),
                ('self_url', models.URLField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
            ],
        ),
    ]
